import type { ThemeColors, ThemeName } from "../types/settings"

export const DEFAULT_THEME: ThemeColors = {
  background: "transparent",
  surface: "#1b1f27",
  primary: "#6fa8ff",
  secondary: "#a9b1d6",
  accent: "#f6c177",
  text: "#e6edf3",
  muted: "#7d8590",
  warning: "#f0b429",
  error: "#f47067",
  success: "#3fb950",
}

export const THEMES: Record<ThemeName, ThemeColors> = {
  system: DEFAULT_THEME,
  catppuccin: {
    background: "transparent",
    surface: "#1e1e2e",
    primary: "#89b4fa",
    secondary: "#cba6f7",
    accent: "#f9e2af",
    text: "#cdd6f4",
    muted: "#7f849c",
    warning: "#fab387",
    error: "#f38ba8",
    success: "#a6e3a1",
  },
  gruvbox: {
    background: "transparent",
    surface: "#282828",
    primary: "#fabd2f",
    secondary: "#83a598",
    accent: "#fe8019",
    text: "#ebdbb2",
    muted: "#928374",
    warning: "#fabd2f",
    error: "#fb4934",
    success: "#b8bb26",
  },
  tokyo: {
    background: "transparent",
    surface: "#1a1b26",
    primary: "#7aa2f7",
    secondary: "#bb9af7",
    accent: "#e0af68",
    text: "#c0caf5",
    muted: "#565f89",
    warning: "#e0af68",
    error: "#f7768e",
    success: "#9ece6a",
  },
  nord: {
    background: "transparent",
    surface: "#2e3440",
    primary: "#88c0d0",
    secondary: "#81a1c1",
    accent: "#ebcb8b",
    text: "#eceff4",
    muted: "#4c566a",
    warning: "#ebcb8b",
    error: "#bf616a",
    success: "#a3be8c",
  },
  custom: DEFAULT_THEME,
}
